import { useMemo, useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Maximize2, Minimize2, RotateCcw, Code2, Play } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

interface Props {
  code: string;
  isStreaming?: boolean;
}

/**
 * Renders an inline interactive widget (HTML/CSS/JS) generated by Astraz inside a
 * sandboxed iframe. Used for things like "show me the visualization of π".
 *
 * The expected format inside a ```viz fence is either:
 *   - a full HTML document, OR
 *   - a fragment (we wrap it in <html><body>…</body></html>).
 */
export const VizBlock = ({ code, isStreaming }: Props) => {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [showSource, setShowSource] = useState(false);
  const [nonce, setNonce] = useState(0);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const srcDoc = useMemo(() => {
    const body = code.trim();
    const isFullDoc = /<\s*html[\s>]/i.test(body) || /<!doctype/i.test(body);
    const inner = isFullDoc
      ? body
      : `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
            html,body{margin:0;padding:0;background:transparent;color:#fff;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;}
            body{display:flex;align-items:center;justify-content:center;min-height:100vh;padding:12px;box-sizing:border-box;}
            *{box-sizing:border-box;}
            canvas{max-width:100%;height:auto;}
          </style></head><body>${body}</body></html>`;
    return inner;
  }, [code, nonce]);

  // Close fullscreen on Escape
  useEffect(() => {
    if (!expanded) return;
    const handler = (e: KeyboardEvent) => e.key === "Escape" && setExpanded(false);
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [expanded]);

  // Collapsed "Show me the visualization" CTA
  if (!open) {
    return (
      <motion.button
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        onClick={() => setOpen(true)}
        disabled={isStreaming}
        className={cn(
          "my-3 group relative w-full overflow-hidden rounded-2xl border border-border/60",
          "bg-gradient-to-br from-xai-purple/15 via-secondary/40 to-xai-cyan/15",
          "px-4 py-3.5 text-left transition-all hover:border-xai-purple/50",
          "disabled:opacity-60 disabled:cursor-not-allowed"
        )}
      >
        <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity bg-gradient-to-br from-xai-purple/10 to-xai-cyan/10 pointer-events-none" />
        <div className="relative flex items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-xai-purple to-xai-cyan shadow-lg shadow-xai-purple/30">
            {isStreaming ? (
              <Sparkles className="h-5 w-5 text-white animate-pulse" />
            ) : (
              <Play className="h-5 w-5 text-white fill-white" />
            )}
          </div>
          <div className="min-w-0 flex-1">
            <div className="text-sm font-semibold text-foreground">
              {isStreaming ? "Preparing visualization…" : "Show me the visualization"}
            </div>
            <div className="text-[11px] text-muted-foreground mt-0.5">
              Interactive widget · tap to run
            </div>
          </div>
        </div>
      </motion.button>
    );
  }

  const frame = (
    <iframe
      key={nonce}
      ref={iframeRef}
      title="Astraz visualization"
      sandbox="allow-scripts allow-pointer-lock allow-popups"
      srcDoc={srcDoc}
      className={cn(
        "w-full border-0 bg-black/60",
        expanded ? "h-full" : "h-[380px] sm:h-[440px]"
      )}
    />
  );

  const toolbar = (
    <div className="flex items-center justify-between gap-2 px-3 py-2 border-b border-border/60 bg-background/80 backdrop-blur">
      <div className="flex items-center gap-2 min-w-0">
        <div className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-xai-purple to-xai-cyan">
          <Sparkles className="h-3.5 w-3.5 text-white" />
        </div>
        <span className="text-xs font-medium text-foreground truncate">Interactive visualization</span>
      </div>
      <div className="flex items-center gap-1">
        <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => setNonce((n) => n + 1)} title="Restart">
          <RotateCcw className="h-3.5 w-3.5" />
        </Button>
        <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => setShowSource((s) => !s)} title="View source">
          <Code2 className={cn("h-3.5 w-3.5", showSource && "text-xai-purple")} />
        </Button>
        <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => setExpanded((e) => !e)} title={expanded ? "Collapse" : "Expand"}>
          {expanded ? <Minimize2 className="h-3.5 w-3.5" /> : <Maximize2 className="h-3.5 w-3.5" />}
        </Button>
      </div>
    </div>
  );

  return (
    <>
      <motion.div
        layout
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        className="my-3 w-full overflow-hidden rounded-2xl border border-border/60 bg-card/60 shadow-[0_10px_40px_-15px_hsl(var(--xai-purple)/0.4)]"
      >
        {toolbar}
        <div className="relative bg-gradient-to-br from-background to-secondary/20">
          {frame}
        </div>
        <AnimatePresence>
          {showSource && (
            <motion.pre
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-auto max-h-64 text-[11px] leading-relaxed p-3 bg-secondary/40 border-t border-border/60 font-mono text-muted-foreground"
            >
              {code}
            </motion.pre>
          )}
        </AnimatePresence>
      </motion.div>

      {/* Fullscreen overlay */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-background/95 backdrop-blur-md flex flex-col"
          >
            {toolbar}
            <div className="flex-1 min-h-0">{frame}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};
